#!/usr/bin/env php
<?php

if ( 'cli' !== PHP_SAPI )
{
    echo 'Warning: Slicer Update should be invoked via the CLI version of PHP, not the ' . PHP_SAPI . ' SAPI' . PHP_EOL;
}

//require __DIR__ . '/vendor/autoload.php';

use Slicer\Contract\IUpdate;

if ( function_exists( 'ini_set' ) )
{
    @ini_set( 'display_errors', 1 );

    $memoryInBytes = function ( $value )
    {
        $unit  = strtolower( substr( $value, -1, 1 ) );
        $value = ( int ) $value;

        switch ( $unit )
        {
            case 'g':
                $value *= 1024;
            // no break ( cumulative multiplier )
            case 'm':
                $value *= 1024;
            // no break ( cumulative multiplier )
            case 'k':
                $value *= 1024;
        }

        return $value;
    };

    $memoryLimit = trim( ini_get( 'memory_limit' ) );

    // Increase memory_limit if it is lower then 1GB

    if ( -1 != $memoryLimit && $memoryInBytes( $memoryLimit ) < 1024 * 1024 * 1024 )
    {
        @ini_set( 'memory_limit', '1G' );
    }

    unset( $memoryInBytes, $memoryLimit );
}

die( 'Update Running - Exiting...' );
?>

//try
//{
//    /** @var IUpdate $update */
//    $update = new Slicer\Update();
//
//    $update->updateFiles();
//    $update->deleteFiles();
//    $update->updateDatabase();
//}
//catch ( Exception $e )
//{
//    $update->rollbackDatabaseChanges();
//    $update->rollbackDeleteFiles();
//    $update->rollbackUpdateFiles();
//}